#!/usr/bin/sh

action=$(echo -e "Shutdown\nReboot\nHibernate\nLogout\nCancel" | dmenu -l 6 -c -bw 1 -i -p "Logout")

if [[ -z "$action" || "$action" == "Cancel" ]]; then
    exit
fi

confirm=$(echo -e "Yes\nNo" | dmenu -l 2 -c -bw 1 -i -p "${action} now?" | tr "[:lower:]" "[:upper:]")

if [[ "$confirm" == "YES" ]]; then
    case $action in
        Shutdown)   systemctl poweroff ;;
        Reboot)     systemctl reboot ;;
        Hibernate)  systemctl hibernate ;;
        Logout)     xdotool key "super+shift+q" ;;
        *)          ;;
    esac
fi

