#!/usr/bin/sh

battery_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
state=$(echo "$battery_info" | grep "state" | awk '{print $2}')
perc=$(echo "$battery_info" | grep "percentage" | awk '{print $2}' | sed "s/%//")
remtime=$(echo "$battery_info" | grep "time to" | awk '{ if ($5 == "hours") printf("%.0f:%02.0f %s", $4, ($4%1) * 60, $5); else printf("%.0f %s", $4, $5); }')

if [ "$perc" -gt 87 ]; then
    echo -n " "
elif [ "$perc" -gt 63 ]; then
    echo -n " "
elif [ "$perc" -gt 38 ]; then
    echo -n " "
elif [ "$perc" -gt 13 ]; then
    echo -n " "
else
    echo -n " "
fi

if [ "$state" = "charging" ] || [ "$state" = "fully-charged" ]; then
    echo -n " "
fi
echo " ${perc}%"

case $BUTTON in
    1|3)
        if [ -n "$remtime" ]; then
            msg="Remaining time: $remtime"
        else
            msg="Remaining time: N/A"
        fi
        notify-send -u low "Battery: ${perc}%" "$msg"
esac
