#!/usr/bin/sh

case $BUTTON in
    1|3)
        today=$(date '+%e' | sed 's/^\s*//')
        month=$(cal | head -1)
        days=$(cal | tail -n +2 | sed "0,/$today/{s|$today|<b>$today</b>|}")
        notify-send -u low "$month" "$days"
        ;;
esac

date '+%a %b %d %H:%M'
