#!/usr/bin/sh

wifistate="$(cat /sys/class/net/w*/operstate 2>/dev/null)"
ethstate="$(cat /sys/class/net/e*/operstate 2>/dev/null)"

if [ "$ethstate" = "up" ]; then
    icon=""   #
elif [ "$wifistate" = "up" ]; then
    icon="直"
else
    icon="睊"
fi


update_traffic() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update_traffic /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update_traffic /sys/class/net/[ew]*/statistics/tx_bytes)

printf "%s  %4sB  %4sB\\n" $icon $(numfmt --to=iec $tx) $(numfmt --to=iec $rx)
