#!/bin/bash

# Check if any players are running
status="$(playerctl status 2>/dev/null)"
if [[ "$?" != 0 || "$status" == "Stopped" ]]; then
    echo " "

    case $BUTTON in
        1|3) deadbeef & disown ;;
    esac

    exit 0
fi

if [[ "$status" == "Playing" ]]; then
    icon="契"
elif [[ "$status" == "Paused" ]]; then
    icon=""
else
    icon=""
fi

# For Spotify, the 'position' field doesn't work
if [[ "$(playerctl metadata -f '{{ playerName }}')" == "spotify" ]]; then
    printf " %s %s" "$icon" "$(playerctl metadata -f '{{ artist }} - {{ title }}')"
else
    printf " %s %s" "$icon" "$(playerctl metadata -f '{{ artist }} - {{ title }} ({{ duration(position) }}/{{ duration(mpris:length) }})')"
fi

