#!/bin/bash

# Check updates with the pacman package manager in ArchLinux
updates="$(checkupdates | awk '{print $1}')"
numupdates="$(printf "%s" "$updates" | wc -l)"

# Count the last linebreak only if the output isn't empty
if [[ "$numupdates" != 0 ]]; then
    numupdates="$(($numupdates + 1))"
fi

printf " %d" $numupdates

case $BUTTON in
    1)
        msg="$(printf "%s" "$updates" | head)"
        if [[ "$numupdates" -gt 10 ]]; then
            msg+="\nand $(($numupdates - 10)) more"
        fi
        msg+="\nRight-click to open terminal"
        notify-send --urgency=low "$numupdates updates available" "$msg"
        ;;
    3)
        st -e zsh -c "sudo pacman -Syu; exec zsh"
        ;;
esac

