#!/usr/bin/sh

case $BUTTON in
    1) pamixer -t && pkill -RTMIN+12 dwmblocks ;;
    3) pavucontrol & disown
esac

if [ "$(pamixer --get-mute)" = "true" ]; then
    echo "婢"
    exit
fi

vol=$(pamixer --get-volume)

if [ "$vol" -gt 67 ]; then
    icon="墳"
elif [ "$vol" -gt 33 ]; then
    icon="奔"
else
    icon="奄"
fi

echo "${icon} ${vol}%"

